-- vim.g.coq_settings = {
-- 	auto_start = true, -- if you want to start COQ at startup
-- 	clients = {
-- 		lsp = {
-- 			always_on_top = {},
-- 		},
-- 	},
-- 	completion = { skip_after = {
-- 		"{",
-- 		"}",
-- 		"[",
-- 		"]",
-- 	} },
-- 	keymap = {
-- 		pre_select = true,
-- 	},
-- 	display = {
-- 		ghost_text = {
-- 			enabled = false,
-- 		},
-- 		pum = {
-- 			y_max_len = 8,
-- 		},
-- 		statusline = { helo = false },
-- 		preview = {
-- 			positions = {
-- 				north = 4,
-- 				south = 3,
-- 				west = 2,
-- 				east = 1,
-- 			},
-- 		},
-- 	},
-- }
--
-- vim.cmd("COQnow")
