require("config.options")
require("config.keymaps").setup()
require("config.keymaps").lsp()
require("config.ui")
require("config.commands")
require("config.autocmd")
-- require("config.ui")
-- -- require("config.lsp")
-- require("config.commands")
-- require("config.diagnostics")
