require("config.options")
require("config.lsp")
-- require("config.statusline")
require("config.commands")
require("config.diagnostics")
-- require("config.ui")
require("config.keymaps").setup()
-- require("config.autocmd")
