require("lsp.diagnostics").setup()
require("lsp.servers").setup()
require("lsp.commands")

vim.lsp.enable("lua_ls")
vim.lsp.enable("ts_ls")
vim.lsp.enable("biome")
vim.lsp.enable("cssmodules_ls")
vim.lsp.enable("css_variables")
vim.lsp.enable("cssls")
vim.lsp.enable("jdtls")
